// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjbftjwiwpfertsljxxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqYmZ0andpd3BmZXJ0c2xqeHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzUwMzMsImV4cCI6MjA3Mzk1MTAzM30.Cm2LW0yhKGrbMBRSkJe4-1-d-6-6Sd3TMx0ouMhXlc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});